const { query } = require('express');
const express = require('express');
const app = express(); 
const bcrypt = require('bcrypt');

const pool = require('../db/database');

/**
 * @swagger
 * components:
 *  schemas:
 *      user:
 *          type: object
 *          required:
 *              -   username
 *              -   email
 *              -   password
 *              -   deleted
 *          properties:
 *              id:
 *                  type: integer
 *                  description: autogenerated id
 *              username:
 *                  type: varchar(50)
 *                  description: user name
 *              address_id:
 *                  type: integer
 *                  description: Foreign key to address table
 *              role_id:
 *                  type: integer
 *                  description: Foreign key to role table
 *              first_name:
 *                  type: varchar(50)
 *                  description: user first name
 *              last_name:
 *                  type: varchar(50)
 *                  description: user last name
 *              email: 
 *                  type: varchar(50)
 *                  description: user email address
 *              telephone_number:
 *                  type: varchar(50)
 *                  description: user telephone number
 *              password: 
 *                  type: varchar(200)
 *                  description: encrypted user password
 *              deleted:
 *                  type: boolean
 *                  description: user deletion indicator
 *          example:
 *              id:3
 *              username: "test_user"
 *              address_id: 3
 *              role_id: 1
 *              first_name: "Test"
 *              last_name: "User"
 *              email: "testuser@api.com"
 *              telephone_number: "+34897564456"
 *              password: "$2b$10$6WUwFrq4cznTgSiB6VJSk.lBgoZmO7P8.7ORIByJuwLLhidMxStxG"
 *              deleted: false
 *              
 */



app.post('/', (req, res, next) => {
    // CHECK WHAT IS THE PREVIOUS USER's ID - NO SEQUENCE IN DB
    pool.query('SELECT MAX(id) FROM users;', (err, result) => {
        console.log(req.body);
        if(err){
            next(err);
        }
        else{
            const {max} = result.rows[0]; 
            console.log(max);
            req.body.userId = max + 1;
            next();
        }    
})
    }, 
    // IF THERE´S ADDRESS INFO IN THE BODY, A NEW ADDRESS SHOULD BE CREATED
    (req, res, next) => {
        const {streetName, streetNumber, zipcode, city, country, apartmentNumber} = req.body;

        if (streetName && streetNumber && zipcode && city && country) {
            console.log('TODO PARA CREAR ADDRESS')
            const text = 'INSERT INTO address (street_name, street_number, zipcode, city, country, apartment_number) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *;'
            const values = [streetName, streetNumber, zipcode, city, country, apartmentNumber]
            pool.query(text, values, (err, results) => {
                if (err) {
                    next(err);
                } else {
                    const {id} = results.rows[0];
                    req.body.addressId = id;
                    console.log(`ADDRESS: ${JSON.stringify(results.rows)}`);
                    next();
                }
            })
        } else {
            console.log('NO hay datos para crear address')
            console.log(streetName, streetNumber, zipcode, city, country, apartment)
            next();
        }
        
    },
    async (req, res, next) => {
        if(!req.body.userId){
            res.send('NO HAY USUARIOS'); //REVISAR
        } else {
            const text = 'INSERT INTO users (id, username, password, address_id, role_id, first_name, last_name, email, telephone_number) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *;';
            const {userId, userName, password, addressId, roleId, firstName, lastName, email, telephoneNumber} = req.body;
            console.log(`SOME BODY: ${JSON.stringify(req.body)}`);
            const hashedPassword = await bcrypt.hash(password, 10);
            console.log(hashedPassword);
            if(userName && password && firstName && lastName && email) {
                pool.query(text, [userId, userName, hashedPassword, addressId, roleId, firstName, lastName, email, telephoneNumber], (err, result) => {
                    if (err){
                        next(err);
                        
                    } else {
                        console.log(`USER :${JSON.stringify((result.rows))}`)
                        res.json(result.rows);
                    }
                })

            } else {
                console.log('Please fill the required fields')
                res.status(500).send('Please fill the required fields')
            }

        }
    }, (err, req, res, next) => {
        console.error(`Error: ${err}`);
        res.status(500).send('Something broke!');
    })
    
    

module.exports = app;
